#server:
#  port: 8081
#
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/marco-cabrejos/everis-entregable-1.git
#          searchPaths: config-data
#          username: ${GITUSER}
#          password: ${GITPASS}
          
server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arodriguezcu/Proyecto2-ConfigData.git
          searchPaths: config-data
#          username: ${GITUSER}
#          password: ${GITPASS}
          default-label: main
