version: "3"

services:
  web:
    container_name: purchase-service
    restart: always
    build: .
    ports:
       - "8092:8092"
    links:
      - mongo
  mongo:
    container_name: purchase-db
    image: mongo
    ports:
      - "27022:27017"