version: "3"

services:
  web:
    container_name: deposit-service
    restart: always
    build: .
    ports:
       - "8096:8096"
    links:
      - mongo
  mongo:
    container_name: deposit-db
    image: mongo
    ports:
      - "27026:27017"