version: "3"

services:
  web:
    container_name: credit-consumer-service
    restart: always
    build: .
    ports:
       - "8097:8097"
    links:
      - mongo
  mongo:
    container_name: credit-db
    image: mongo
    ports:
      - "27027:27017"