version: "3"

services:
  web:
    container_name: customer-service
    restart: always
    build: .
    ports:
       - "8090:8090"
    links:
      - mongo
  mongo:
    container_name: customer-db
    image: mongo
    ports:
      - "27020:27017"